# Generated by Django 4.2.4 on 2023-09-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserWiki", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikiinformation",
            name="article",
        ),
    ]
