# Generated by Django 4.2.4 on 2023-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserWiki", "0002_remove_wikiinformation_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiinformation",
            name="article",
            field=models.TextField(default=""),
        ),
    ]
